"""baseline

Revision ID: 3bebf458e597
Revises: 
Create Date: 2026-08-06 12:51:04.892898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bebf458e597'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('direccion', sa.String(), nullable=False),
    sa.Column('telefono', sa.String(), nullable=False),
    sa.Column('observaciones', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_direccion'), 'clientes', ['direccion'], unique=False)
    op.create_table('equipos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('marca', sa.String(), nullable=False),
    sa.Column('modelo', sa.String(), nullable=True),
    sa.Column('fecha_instalacion', sa.Date(), nullable=True),
    sa.Column('fecha_ultimo_servi', sa.Date(), nullable=True),
    sa.Column('observaciones', sa.String(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipos_id'), 'equipos', ['id'], unique=False)
    op.create_table('aires_acondicionados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('frigorias', sa.Integer(), nullable=False),
    sa.Column('tipo_aire', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['equipos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('heladeras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('capac_litros', sa.Integer(), nullable=False),
    sa.Column('tipo_heladera', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['equipos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lavarropas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('capac_kilos', sa.Integer(), nullable=False),
    sa.Column('tipo_lavarropas', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['equipos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('servicios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_servicio', sa.Enum('INSTALACION', 'SERVICE', 'REPARACION', name='tiposervicioenum', native_enum=False), nullable=False),
    sa.Column('fecha_serv', sa.Date(), nullable=False),
    sa.Column('observaciones', sa.String(), nullable=True),
    sa.Column('fecha_prox_serv', sa.Date(), nullable=True),
    sa.Column('equipo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_servicios_id'), 'servicios', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_servicios_id'), table_name='servicios')
    op.drop_table('servicios')
    op.drop_table('lavarropas')
    op.drop_table('heladeras')
    op.drop_table('aires_acondicionados')
    op.drop_index(op.f('ix_equipos_id'), table_name='equipos')
    op.drop_table('equipos')
    op.drop_index(op.f('ix_clientes_direccion'), table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###
