"""direccion_cliente_opcional

Revision ID: edec000fd991
Revises: 3bebf458e597
Create Date: 2026-08-06 12:58:24.528732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edec000fd991'
down_revision: Union[str, Sequence[str], None] = '3bebf458e597'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clientes', 'direccion',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clientes', 'direccion',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
